import {
  Cushion,
  Fit,
  PrismaClient,
  Stability,
} from '@prisma/client';
import { getCuratedUnsplashImage } from '../src/utils/unsplash';

const prisma = new PrismaClient();

async function main() {
  // Delete in order to respect foreign key constraints
  await prisma.reviewVote.deleteMany();
  await prisma.review.deleteMany();
  await prisma.shoe.deleteMany();
  await prisma.user.deleteMany();

  const users = await Promise.all(
    [
      {
        name: 'Alice Runner',
        email: 'alice@example.com',
        password: 'hashed-password-alice',
        weight: 62,
        pace: 4.5,
      },
      {
        name: 'Ben Sprinter',
        email: 'ben@example.com',
        password: 'hashed-password-ben',
        weight: 75,
        pace: 3.8,
      },
      {
        name: 'Chloe Trail',
        email: 'chloe@example.com',
        password: 'hashed-password-chloe',
        weight: 68,
        pace: 5.2,
      },
      {
        name: 'Diego Tempo',
        email: 'diego@example.com',
        password: 'hashed-password-diego',
        weight: 70,
        pace: 4.1,
      },
      {
        name: 'Emma Ultra',
        email: 'emma@example.com',
        password: 'hashed-password-emma',
        weight: 58,
        pace: 5,
      },
      {
        name: 'Felix Marathon',
        email: 'felix@example.com',
        password: 'hashed-password-felix',
        weight: 82,
        pace: 4.6,
      },
      {
        name: 'Gianna Cadence',
        email: 'gianna@example.com',
        password: 'hashed-password-gianna',
        weight: 60,
        pace: 4.9,
      },
      {
        name: 'Henry Strong',
        email: 'henry@example.com',
        password: 'hashed-password-henry',
        weight: 90,
        pace: 4.3,
      },
      {
        name: 'Isla Recovery',
        email: 'isla@example.com',
        password: 'hashed-password-isla',
        weight: 55,
        pace: 5.4,
      },
      {
        name: 'Jack Strider',
        email: 'jack@example.com',
        password: 'hashed-password-jack',
        weight: 78,
        pace: 4,
      },
    ].map((data) => prisma.user.create({ data })),
  );

  const [
    alice,
    ben,
    chloe,
    diego,
    emma,
    felix,
    gianna,
    henry,
    isla,
    jack,
  ] = users;

  const shoes = await Promise.all(
    [
      {
        brand: 'Asics',
        model: 'GlideRide 4',
        type: 'Long run',
        stackHeight: 37,
        drop: 5,
        weightGrams: 276,
        releaseYear: 2024,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('Asics', 'GlideRide 4'),
      },
      {
        brand: 'Saucony',
        model: 'Endorphin Speed 4',
        type: 'Tempo',
        stackHeight: 36,
        drop: 8,
        weightGrams: 229,
        releaseYear: 2025,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('Saucony', 'Endorphin Speed 4'),
      },
      {
        brand: 'Inov-8',
        model: 'TerraUltra G 270',
        type: 'Trail',
        stackHeight: 21,
        drop: 0,
        weightGrams: 270,
        releaseYear: 2023,
        category: 'Trail',
        imageUrl: getCuratedUnsplashImage('Inov-8', 'TerraUltra G 270'),
      },
      {
        brand: 'Nike',
        model: 'Invincible 3',
        type: 'Easy',
        stackHeight: 40,
        drop: 9,
        weightGrams: 310,
        releaseYear: 2024,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('Nike', 'Invincible 3'),
      },
      {
        brand: 'Brooks',
        model: 'Hyperion Max',
        type: 'Uptempo',
        stackHeight: 34,
        drop: 8,
        weightGrams: 207,
        releaseYear: 2024,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('Brooks', 'Hyperion Max'),
      },
      {
        brand: 'Adidas',
        model: 'Adizero Adios Pro 3',
        type: 'Racing',
        stackHeight: 39.5,
        drop: 6.5,
        weightGrams: 215,
        releaseYear: 2024,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('Adidas', 'Adizero Adios Pro 3'),
      },
      {
        brand: 'New Balance',
        model: 'FuelCell Rebel v4',
        type: 'Daily trainer',
        stackHeight: 32,
        drop: 6,
        weightGrams: 212,
        releaseYear: 2025,
        category: 'Neutral',
        imageUrl: getCuratedUnsplashImage('New Balance', 'FuelCell Rebel v4'),
      },
    ].map((data) => prisma.shoe.create({ data })),
  );

  const [
    glideRide,
    endorphinSpeed,
    terraUltra,
    nikeInvincible,
    brooksHyperionMax,
    adiosPro3,
    rebel4,
  ] = shoes;

  void nikeInvincible;

  const reviewData = [
    {
      rating: 5,
      comment:
        'GlideRide 4 keeps my legs fresh on marathon build-up long runs.',
      shoeId: glideRide.id,
      userId: alice.id,
      pace: 4.45,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 180,
      paceMinutes: 4,
      paceSeconds: 27,
      weight: 62,
    },
    {
      rating: 4,
      comment:
        'Rockered ride helps me hold pace on steady aerobic days.',
      shoeId: glideRide.id,
      userId: diego.id,
      pace: 4.12,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 140,
      paceMinutes: 4,
      paceSeconds: 7,
      weight: 70,
    },
    {
      rating: 4,
      comment:
        'Upper breathes well on warm morning runs.',
      shoeId: glideRide.id,
      userId: emma.id,
      pace: 5.05,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.SOFT,
      stability: Stability.NEUTRAL,
      mileage: 120,
      paceMinutes: 5,
      paceSeconds: 3,
      weight: 58,
    },
    {
      rating: 5,
      comment:
        'Keeps calves fresh after back-to-back long runs.',
      shoeId: glideRide.id,
      userId: henry.id,
      pace: 4.3,
      fit: Fit.BIG,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 210,
      paceMinutes: 4,
      paceSeconds: 18,
      weight: 90,
    },
    {
      rating: 4,
      comment:
        'Smooth transitions, could use more toe box room.',
      shoeId: glideRide.id,
      userId: gianna.id,
      pace: 4.85,
      fit: Fit.SMALL,
      cushion: Cushion.SOFT,
      stability: Stability.NEUTRAL,
      mileage: 160,
      paceMinutes: 4,
      paceSeconds: 51,
      weight: 60,
    },
    {
      rating: 3,
      comment:
        'Midsole starts to feel flat past 250 km.',
      shoeId: glideRide.id,
      userId: felix.id,
      pace: 4.6,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 260,
      paceMinutes: 4,
      paceSeconds: 36,
      weight: 82,
    },
    {
      rating: 5,
      comment:
        'Perfect for easy recovery jogs on tired legs.',
      shoeId: glideRide.id,
      userId: isla.id,
      pace: 5.4,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.SOFT,
      stability: Stability.NEUTRAL,
      mileage: 90,
      paceMinutes: 5,
      paceSeconds: 24,
      weight: 55,
    },
    {
      rating: 4,
      comment:
        'Super responsive for track sessions, though lockdown could be snugger.',
      shoeId: endorphinSpeed.id,
      userId: ben.id,
      pace: 3.75,
      fit: Fit.SMALL,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 95,
      paceMinutes: 3,
      paceSeconds: 45,
      weight: 75,
    },
    {
      rating: 5,
      comment:
        'Snappy turnover for threshold intervals.',
      shoeId: endorphinSpeed.id,
      userId: alice.id,
      pace: 4,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 75,
      paceMinutes: 4,
      paceSeconds: 0,
      weight: 62,
    },
    {
      rating: 4,
      comment:
        'Springy ride keeps me light on my feet during fartleks.',
      shoeId: endorphinSpeed.id,
      userId: diego.id,
      pace: 3.95,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 110,
      paceMinutes: 3,
      paceSeconds: 57,
      weight: 70,
    },
    {
      rating: 5,
      comment:
        'Plated snap makes tempo runs fun.',
      shoeId: endorphinSpeed.id,
      userId: emma.id,
      pace: 4.5,
      fit: Fit.SMALL,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 130,
      paceMinutes: 4,
      paceSeconds: 30,
      weight: 58,
    },
    {
      rating: 4,
      comment:
        'Slight heel slip but ride is addictive.',
      shoeId: endorphinSpeed.id,
      userId: felix.id,
      pace: 4.4,
      fit: Fit.BIG,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 150,
      paceMinutes: 4,
      paceSeconds: 24,
      weight: 82,
    },
    {
      rating: 5,
      comment:
        'Effortless acceleration for progression runs.',
      shoeId: endorphinSpeed.id,
      userId: gianna.id,
      pace: 4.3,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 100,
      paceMinutes: 4,
      paceSeconds: 18,
      weight: 60,
    },
    {
      rating: 4,
      comment:
        'Great track feel, wish outsole gripped better in rain.',
      shoeId: endorphinSpeed.id,
      userId: jack.id,
      pace: 3.85,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 80,
      paceMinutes: 3,
      paceSeconds: 51,
      weight: 78,
    },
    {
      rating: 5,
      comment:
        'Fantastic ground feel on technical trails without beating up my feet.',
      shoeId: terraUltra.id,
      userId: chloe.id,
      pace: 5.35,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.HIGH_SUPPORT,
      mileage: 220,
      paceMinutes: 5,
      paceSeconds: 21,
      weight: 68,
    },
    {
      rating: 5,
      comment:
        'Confident traction on wet roots.',
      shoeId: terraUltra.id,
      userId: diego.id,
      pace: 4.6,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.HIGH_SUPPORT,
      mileage: 150,
      paceMinutes: 4,
      paceSeconds: 36,
      weight: 70,
    },
    {
      rating: 4,
      comment:
        'Roomy toe box saves my toes on ultras.',
      shoeId: terraUltra.id,
      userId: emma.id,
      pace: 5.2,
      fit: Fit.BIG,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 240,
      paceMinutes: 5,
      paceSeconds: 12,
      weight: 58,
    },
    {
      rating: 3,
      comment:
        'Feels a bit harsh on hardpack fire roads.',
      shoeId: terraUltra.id,
      userId: felix.id,
      pace: 4.8,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.HIGH_SUPPORT,
      mileage: 200,
      paceMinutes: 4,
      paceSeconds: 48,
      weight: 82,
    },
    {
      rating: 4,
      comment:
        'Durable outsole handles crushed granite trails.',
      shoeId: terraUltra.id,
      userId: henry.id,
      pace: 4.9,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.HIGH_SUPPORT,
      mileage: 190,
      paceMinutes: 4,
      paceSeconds: 54,
      weight: 90,
    },
    {
      rating: 5,
      comment:
        'Zero drop keeps me stable on technical descents.',
      shoeId: terraUltra.id,
      userId: isla.id,
      pace: 5.55,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.HIGH_SUPPORT,
      mileage: 210,
      paceMinutes: 5,
      paceSeconds: 33,
      weight: 55,
    },
    {
      rating: 4,
      comment:
        'Fast feel without full plate stiffness.',
      shoeId: brooksHyperionMax.id,
      userId: ben.id,
      pace: 3.9,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 120,
      paceMinutes: 3,
      paceSeconds: 54,
      weight: 75,
    },
    {
      rating: 3,
      comment:
        'Forefoot cushioning thin for longer workouts.',
      shoeId: brooksHyperionMax.id,
      userId: alice.id,
      pace: 4.2,
      fit: Fit.SMALL,
      cushion: Cushion.FIRM,
      stability: Stability.NEUTRAL,
      mileage: 95,
      paceMinutes: 4,
      paceSeconds: 12,
      weight: 62,
    },
    {
      rating: 4,
      comment:
        'Responsive enough for strides after trail blocks.',
      shoeId: brooksHyperionMax.id,
      userId: chloe.id,
      pace: 5.1,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 80,
      paceMinutes: 5,
      paceSeconds: 6,
      weight: 68,
    },
    {
      rating: 5,
      comment:
        'Snappy toe-off for cruise intervals.',
      shoeId: brooksHyperionMax.id,
      userId: diego.id,
      pace: 4.05,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 140,
      paceMinutes: 4,
      paceSeconds: 3,
      weight: 70,
    },
    {
      rating: 4,
      comment:
        'Lightweight feel keeps cadence high.',
      shoeId: brooksHyperionMax.id,
      userId: gianna.id,
      pace: 4.25,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 110,
      paceMinutes: 4,
      paceSeconds: 15,
      weight: 60,
    },
    {
      rating: 3,
      comment:
        'Wish heel was softer for easy days.',
      shoeId: brooksHyperionMax.id,
      userId: jack.id,
      pace: 3.95,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 130,
      paceMinutes: 3,
      paceSeconds: 57,
      weight: 78,
    },
    {
      rating: 5,
      comment:
        'Race-day rocket with aggressive rocker.',
      shoeId: adiosPro3.id,
      userId: ben.id,
      pace: 3.65,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.NEUTRAL,
      mileage: 60,
      paceMinutes: 3,
      paceSeconds: 39,
      weight: 75,
    },
    {
      rating: 4,
      comment:
        'Carbon rods feel springy on tempo efforts.',
      shoeId: adiosPro3.id,
      userId: felix.id,
      pace: 3.8,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.FIRM,
      stability: Stability.NEUTRAL,
      mileage: 90,
      paceMinutes: 3,
      paceSeconds: 48,
      weight: 82,
    },
    {
      rating: 4,
      comment:
        'Holds structure late in the marathon.',
      shoeId: adiosPro3.id,
      userId: henry.id,
      pace: 3.95,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 70,
      paceMinutes: 3,
      paceSeconds: 57,
      weight: 90,
    },
    {
      rating: 5,
      comment:
        'Light upper disappears on race pace sessions.',
      shoeId: adiosPro3.id,
      userId: emma.id,
      pace: 4.1,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.BALANCED,
      stability: Stability.NEUTRAL,
      mileage: 85,
      paceMinutes: 4,
      paceSeconds: 6,
      weight: 58,
    },
    {
      rating: 4,
      comment:
        'Forefoot pop is addicting though heel sits narrow.',
      shoeId: adiosPro3.id,
      userId: gianna.id,
      pace: 4.05,
      fit: Fit.SMALL,
      cushion: Cushion.FIRM,
      stability: Stability.MODERATE_SUPPORT,
      mileage: 75,
      paceMinutes: 4,
      paceSeconds: 3,
      weight: 60,
    },
    {
      rating: 5,
      comment:
        'Playful bounce for daily mileage.',
      shoeId: rebel4.id,
      userId: chloe.id,
      pace: 5,
      fit: Fit.TRUE_TO_SIZE,
      cushion: Cushion.SOFT,
      stability: Stability.NEUTRAL,
      mileage: 130,
      paceMinutes: 5,
      paceSeconds: 0,
      weight: 68,
    },
    {
      rating: 4,
      comment:
        'Great for uptempo efforts, forefoot a tad narrow.',
      shoeId: rebel4.id,
      userId: isla.id,
      pace: 5.2,
      fit: Fit.SMALL,
      cushion: Cushion.SOFT,
      stability: Stability.NEUTRAL,
      mileage: 115,
      paceMinutes: 5,
      paceSeconds: 12,
      weight: 55,
    },
  ];

  await prisma.review.createMany({
    data: reviewData,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error('Error seeding database:', error);
    await prisma.$disconnect();
    process.exit(1);
  });

